### PR TITLE
Add DragonOS.

### PR DESCRIPTION
**Pull request by fslongjin**
Hey guys, I've add my DragonOS and hope you will accept my PR~

### CODE REVIEW

**Comment by jubalh** [comment]
Cool, I can't read the language but if I understand correctly then this should go to the hobby section. Would you mind moving it there?

**Comment by fslongjin** [comment]
> Cool, I can't read the language but if I understand correctly then this should go to the hobby section. Would you mind moving it there?

Should I initiate a PR again after modification, or what should I do?

**Comment by fslongjin** [comment]
OK~ I've modified my commit.

**Comment by jubalh** [comment]
Thanks!

**Pull request merged**
