### PR TITLE
Fix Markdown syntax

### PR DESCRIPTION
**Pull request by peutch**

### CODE REVIEW

**Comment by jubalh** [comment]
Please rename to `Fix markdown syntax" or something like that :)

**Comment by jubalh** [comment]
I meant in the commit message not PR title :)
`git commit --amend` `git push -f`

**Comment by peutch** [comment]
I hope it is fine now ;-)

**Comment by jubalh** [comment]
Actually the commit title is still `worng syntax, sorry`.

**Comment by peutch** [comment]
It is ok now?

**Comment by jubalh** [comment]
yep

**Pull request merged**
