### PR TITLE
Add MaslOS

### PR DESCRIPTION
**Pull request by marceldobehere**
would be very cool yes yes

### CODE REVIEW

**Comment by jubalh** [comment]
description is bad

**Comment by marceldobehere** [comment]
of this commit or the description in the readme?

**Comment by jubalh** [comment]
> - A weird black magic

is weird compared to

> an OS written in C++ and a bit of C. The base was made following [Ponchos OS Dev Youtube Playlist](https://www.youtube.com/playlist?list=PLxN4E629pPnJxCQCLy7E0SQY_zuumOVyZ) The OS is now using [limine](https://github.com/limine-bootloader/limine) as the bootloader.

which is nice :)

**Comment by marceldobehere** [comment]
I see. Would the new description be good?

**Comment by jubalh** [comment]
Yes looks good. Please squash the 2 commits into 1.

**Comment by marceldobehere** [comment]
Just did

**Comment by jubalh** [comment]
Thanks

**Pull request merged**
