### PR TITLE
Add GreenteaOS

### PR DESCRIPTION
**Pull request by ZhymabekRoman**

### CODE REVIEW

**Comment by jubalh** [comment]
Not sure what 'warm and cozy' means.
"compatible with existing apps and games " with which apps?

Maybe change the description :-)

**Comment by ZhymabekRoman** [comment]
> Not sure what 'warm and cozy' means.
> "compatible with existing apps and games " with which apps?
> 
> Maybe change the description :-)

Maybe "A free operating system designed for native launch .exe applications" ?

**Comment by jubalh** [comment]
Something like this yeah :) How about: "A free OS designed to be compatible with Windows executables" or windows binaries.

**Comment by ZhymabekRoman** [comment]
> Something like this yeah :) How about: "A free OS designed to be compatible with Windows executables" or windows binaries.

Hmmm, great idea

**Comment by jubalh** [comment]
Thanks!

**Pull request merged**
