### PR TITLE
Cyjon update, Fern-Night added

### PR DESCRIPTION
**Pull request by CorruptedByCPU**
Thank You.

### CODE REVIEW

**Comment by jubalh** [comment]
* you are not updating anything you are adding two projects
* for some reason you write that project A is based on project B but you also write that project B is based on project A. Confusing :)

**Review by jubalh — CHANGES_REQUESTED** [review]
see comment

**Comment by CorruptedByCPU** [comment]
`you are not updating anything you are adding two projects`
Moved Cyjon to Open Source category (modified description) and added Fern-Night to Hobby projects.

`for some reason you write that project A is based on project B but you also write that project B is based on project A. Confusing :)`
and it's true, first there was Cyjon, then I created Fern-Night based on Cyjon (and Lotus-Effect as transition state),
but Fern-Night already deviates so much from Cyjon's code that I have to rewrite Cyjon with all modifications and improvements basing on Fern-Night :)

This is where the chicken and egg problem arose, which came first :D Let others wonder when they don't know history.

**Review by jubalh — CHANGES_REQUESTED** [review]
Please leave/add both projects in the hobby section.
And I prefer the old description since the one that you are adding sounds too much like marketing :)
And maybe remove the `based on` completely because it just confuses people or change it `related to project B`

**Review by jubalh — APPROVED** [review]
Thanks
One commit would have been better though :) But no problem

**Comment by CorruptedByCPU** [comment]
It's my first time editing pull request, sorry about that :)
Thanks.

**Pull request merged**
