### PR TITLE
[+] OS: QUBES

### PR DESCRIPTION
**Pull request by loneicewolf**

### CODE REVIEW

**Comment by jubalh** [comment]
AFAIK that's actually a Linux.

**Comment by loneicewolf** [comment]
> 

Yes? Sorry was it off topic?

**Comment by jubalh** [comment]
Well, I try to collect here various operating systems so people can learn about OS design and how they work. So the main focus is on listing different systems, papers, how tos in this area.
I think distrowatch is already a good overview of a list of all Linux related distributions. And maybe there exist also dedicated awesome lists for that :)

**Comment by loneicewolf** [comment]
> Well, I try to collect here various operating systems so people can learn about OS design and how they work. So the main focus is on listing different systems, papers, how tos in this area. I think distrowatch is already a good overview of a list of all Linux related distributions. And maybe there exist also dedicated awesome lists for that :)

Hi! sorry for the late delay, and Yes thank you! I close this, im sorry for the misunderstanding :)
Have a good day!

**Comment by jubalh** [comment]
No worries! Thanks for understanding.

**Pull request closed without merging**
